(ns om-next-todo.material-ui)

(def app-bar              (js/React.createFactory js/MaterialUI.AppBar))
(def table                (js/React.createFactory js/MaterialUI.Table))
(def table-header         (js/React.createFactory js/MaterialUI.TableHeader))
(def table-header-col     (js/React.createFactory js/MaterialUI.TableHeaderColumn))
(def table-row            (js/React.createFactory js/MaterialUI.TableRow))
(def table-body           (js/React.createFactory js/MaterialUI.TableBody))
(def table-row-col        (js/React.createFactory js/MaterialUI.TableRowColumn))
(def table-footer         (js/React.createFactory js/MaterialUI.TableFooter))
(def flat-button          (js/React.createFactory js/MaterialUI.FlatButton))
(def paper                (js/React.createFactory js/MaterialUI.Paper))
(def icon-button          (js/React.createFactory js/MaterialUI.IconButton))
(def fab                  (js/React.createFactory js/MaterialUI.FloatingActionButton))
(def font-icon            (js/React.createFactory js/MaterialUI.FontIcon))
(def text-field           (js/React.createFactory js/MaterialUI.TextField))
(def dialog               (js/React.createFactory js/MaterialUI.Dialog))
(def checkbox             (js/React.createFactory js/MaterialUI.Checkbox))